var cities = {
  'Moldova': {
    'Anenii Noi',
    'Basarabeasca',
    'Bender',
    'Briceni',
    'Bălţi',
    'Cahul',
    'Cantemir',
    'Chişinău',
    'Cimişlia',
    'Criuleni',
    'Călăraşi',
    'Căuşeni',
    'Donduşeni',
    'Drochia',
    'Dubăsari',
    'Edineţ',
    'Floreşti',
    'Făleşti',
    'Glodeni',
    'Hînceşti',
    'Ialoveni',
    'Leova',
    'Nisporeni',
    'Ocniţa',
    'Orhei',
    'Rezina',
    'Rîşcani',
    'Soroca',
    'Străşeni',
    'Sîngerei',
    'Taraclia',
    'Teleneşti',
    'UTA Găgăuzia',
    'UTA din stinga Nistrului',
    'Ungheni',
    'Şoldăneşti',
    'Ştefan Vodă',
  },
  'Romania': {
    'Bucuresti',
    'Neamt',
    'Ungheni',
    'Soroca',
  },
};
