// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3CdcxO8VZ5vqkjNPh7LFg4amAiyfxElg',
    appId: '1:91914151063:web:b52cc084890d7ffc8d35d2',
    messagingSenderId: '91914151063',
    projectId: 'cligo-app',
    authDomain: 'cligo-app.firebaseapp.com',
    storageBucket: 'cligo-app.appspot.com',
    measurementId: 'G-GT296XXCRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEFzzgb-R8I6y4UuLekfd2IguAZiToXuU',
    appId: '1:91914151063:android:f5c418e9bab890c58d35d2',
    messagingSenderId: '91914151063',
    projectId: 'cligo-app',
    storageBucket: 'cligo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTAn0aKLiXtjipOG0ytNI6T1PEP0DnkFA',
    appId: '1:91914151063:ios:6c453e853141dfff8d35d2',
    messagingSenderId: '91914151063',
    projectId: 'cligo-app',
    storageBucket: 'cligo-app.appspot.com',
    iosClientId: '91914151063-ovlcb8a8cd3fdc0g9atmdti9k98lt8di.apps.googleusercontent.com',
    iosBundleId: 'tech.cligo.cligo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTAn0aKLiXtjipOG0ytNI6T1PEP0DnkFA',
    appId: '1:91914151063:ios:741f5d9263d7179b8d35d2',
    messagingSenderId: '91914151063',
    projectId: 'cligo-app',
    storageBucket: 'cligo-app.appspot.com',
    iosClientId: '91914151063-m4odfqs4lb1a65rv4i81j4qucjdsmsmd.apps.googleusercontent.com',
    iosBundleId: 'tech.cligo.cligo.RunnerTests',
  );
}
