// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxtt0KAWckiJX8PElnnnKxTyFq-YO04ng',
    appId: '1:66077266094:web:c942201f9838fc7d5f9d3f',
    messagingSenderId: '66077266094',
    projectId: 'cligo-app-travel',
    authDomain: 'cligo-app-travel.firebaseapp.com',
    storageBucket: 'cligo-app-travel.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWBUVEtLDtbESxQDvFxQj-1gLdi65quzA',
    appId: '1:66077266094:android:0f7b6fc6f6563f255f9d3f',
    messagingSenderId: '66077266094',
    projectId: 'cligo-app-travel',
    storageBucket: 'cligo-app-travel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTdTj6xiwD3SF-YNQDYWfRdmw53140Mnk',
    appId: '1:66077266094:ios:d18efe4428cbf45d5f9d3f',
    messagingSenderId: '66077266094',
    projectId: 'cligo-app-travel',
    storageBucket: 'cligo-app-travel.appspot.com',
    iosClientId: '66077266094-8rhv2s8rqmf7f8ksgo5enliklu8rgh9k.apps.googleusercontent.com',
    iosBundleId: 'tech.cligo.cligo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTdTj6xiwD3SF-YNQDYWfRdmw53140Mnk',
    appId: '1:66077266094:ios:31de99263aa79ab45f9d3f',
    messagingSenderId: '66077266094',
    projectId: 'cligo-app-travel',
    storageBucket: 'cligo-app-travel.appspot.com',
    iosClientId: '66077266094-7c5f79rq3id1b5ff3bt8po9qnlgfr23c.apps.googleusercontent.com',
    iosBundleId: 'tech.cligo.cligo.RunnerTests',
  );
}
